services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: gitlab.homelab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.homelab:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2289
    ports:
      - "8929:8080"
      - "2289:22"
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
    shm_size: "1g"

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: always
    depends_on:
      - gitlab
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./runner-config:/etc/gitlab-runner
