# workloads/nginx-simple/03-ingress.yml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-nginx-ingress
  namespace: default
spec:
  ingressClassName: nginx # Diz ao Ingress-Nginx para usar este
  rules:
  - host: hello.172.20.1.61.nip.io # O mesmo hostname de antes
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-nginx-svc # O nome do nosso Servi√ßo
            port:
              name: http